import { createSlice, createAsyncThunk } from "@reduxjs/toolkit";
import axios from "axios";
//way of creating a slice of the state, we will create a slice for the products, which will contain the products and the functions that will change the state of the products

//doubt: what is the purpose of createAsyncThunk and how to use it?
//createAsyncThunk is a function that allows us to create a thunk that will handle the asynchronous logic of fetching the products from the backend, it takes two arguments, the first one is the name of the thunk and the second one is a function that will contain the logic of fetching the products, it returns a promise that will be resolved with the data fetched from the backend or rejected with an error if something goes wrong
export const getProduct = createAsyncThunk("product/getProduct", async ({ keyword, page = 1 ,category}, { rejectWithValue }) => {
    try {
        // const link = keyword ? `/api/v1/products?keyword=${encodeURIComponent(keyword)}&page=${page}` : `/api/v1/products?page=${page}`
        let link = `/api/v1/products?page=`+page
        if(keyword){
            link += `&keyword=${encodeURIComponent(keyword)}`
        }
        if(category){
            link += `&category=${encodeURIComponent(category)}`
        }
        const { data } = await axios.get(link)
        console.log('data from backend', data)
        return data

    } catch (error) {
        const errorMsg = error.response?.data?.message || error.message || "Something went wrong"
        return rejectWithValue({ message: errorMsg })
    }
})

export const getProductDetails = createAsyncThunk("product/getProductDetails", async (id, rejectWithValue) => {
    try {
        const link = `/api/v1/product/${id}`
        const { data } = await axios.get(link) 
        console.log('data from backend', data)
        return data

    } catch (error) {
        const errorMsg = error.response?.data?.message || error.message || "Something went wrong"
        return rejectWithValue({ message: errorMsg })
    }
})


const productSlice = createSlice({
    name: "products",
    initialState: {
        products: [],
        productCount: 0,
        loading: false,
        error: null,
        product: null,
        resultsPerPage: 0,
        totalPages: 0
    },
    //reducers meaning the functions that will change the state of the products, we will dispatch these functions in our components to change the state of the products
    reducers: {
        removeErrors: (state) => {
            state.error = null
        }
    },
    //doubt: what is the purpose of extraReducers and how to use it?
    //extraReducers is a function that allows us to handle the actions generated by the createAsyncThunk, it takes a builder as an argument, which is an object that contains the methods to handle the actions generated by the createAsyncThunk, we can use the addCase method of the builder to handle the pending, fulfilled and rejected actions generated by the createAsyncThunk, we can also use the addMatcher method to handle multiple actions at once, we can also use the addDefaultCase method to handle any action that is not handled by the addCase or addMatcher methods
    extraReducers: (builder) => {
        builder.addCase(getProduct.pending, (state) => {
            state.loading = true
        })
            .addCase(getProduct.fulfilled, (state, action) => {
                console.log('fullfilled action payload', action.payload)
                state.loading = false
                state.error = null
                state.products = action.payload.products
                state.productCount = action.payload.productCount
                state.resultsPerPage = action.payload.resultPerPage
                state.totalPages = action.payload.totalPages
            })
            .addCase(getProduct.rejected, (state, action) => {
                state.loading = false
                state.error = action.payload || "Something went wrong"
                state.products = []
            })

        builder.addCase(getProductDetails.pending, (state, action) => {
            state.loading = true
            state.error = null
        })
            .addCase(getProductDetails.fulfilled, (state, action) => {
                console.log('product details', action.payload)
                state.loading = false
                state.error = null
                state.product = action.payload.product
            })
            .addCase(getProductDetails.rejected, (state, action) => {
                state.loading = false
                state.error = action.payload || "Something went wrong"
            })
    }
})

export const { removeErrors } = productSlice.actions
export default productSlice.reducer;